export const COLORS = {
    light: {
        background: '#000935',
        blockBackground: '#0F1953',
        regularText: '#ffffff',
        additionalText: '#FCEBD4',
        subText: '#AFCBE0',
        buttonGradientStart: '#130409',
        buttonGradientEnd: '#570034',
        focusedTab: '#FCEBD4',
        blurredTab: '#7C6974',
        tabBarBackground: '#000A40',
    },
    dark: {
        background: '#000935',
        blockBackground: '#0F1953',
        regularText: '#ffffff',
        additionalText: '#FCEBD4',
        subText: '#FCEBD4',
        buttonGradientStart: '#130409',
        buttonGradientEnd: '#570034',
        focusedTab: '#FCEBD4',
        blurredTab: '#7C6974',
        tabBarBackground: '#000A40',
    },
};
